""" Spells"""

from enum import StrEnum, auto


class Spells(StrEnum):
    AID = auto()
    ALARM = auto()
    ANIMAL_FRIENDSHIP = auto()
    ANIMAL_MESSENGER = auto()
    BARKSKIN = auto()
    BEAST_SENSE = auto()
    COMMUNE_WITH_NATURE = auto()
    CONJURE_ANIMALS = auto()
    CONJURE_WOODLAND_ANIMALS = auto()
    CORDON_OF_ARROWS = auto()
    CURE_WOUNDS = auto()
    DARKVISION = auto()
    DAYLIGHT = auto()
    DETECT_MAGIC = auto()
    DETECT_POISON_AND_DISEASE = auto()
    DISPEL_MAGIC = auto()
    DOMINATE_BEAST = auto()
    ENHANCE_ABILITY = auto()
    ENSNARING_STRIKE = auto()
    ENTANGLE = auto()
    FIND_TRAPS = auto()
    FOG_CLOUD = auto()
    FREEDOM_OF_MOVEMENT = auto()
    GOODBERRY = auto()
    GREATER_RESTORATION = auto()
    GUST_OF_WIND = auto()
    HAIL_OF_THORNS = auto()
    HUNTERS_MARK = auto()
    JUMP = auto()
    LESSER_RESTORATION = auto()
    LOCATE_ANIMALS_OR_PLANTS = auto()
    LOCATE_CREATURE = auto()
    LOCATE_OBJECT = auto()
    LONGSTRIDER = auto()
    MAGIC_WEAPON = auto()
    MELD_INTO_STONE = auto()
    NONDETECTION = auto()
    PASS_WITHOUT_TRACE = auto()
    PLANT_GROWTH = auto()
    PROTECTION_FROM_ENERGY = auto()
    PROTECTION_FROM_POISON = auto()
    REVIVIFY = auto()
    SILENCE = auto()
    SPEAK_WITH_ANIMALS = auto()
    SPEAK_WITH_PLANTS = auto()
    SPIKE_GROWTH = auto()
    STONESKIN = auto()
    SUMMON_BEAST = auto()
    TREE_STRIDE = auto()
    WATER_BREATHING = auto()
    WATER_WALK = auto()
    WIND_WALL = auto()


# EOF
