""" Spells"""

from enum import StrEnum, auto


class Spells(StrEnum):
    AID = auto()
    ALARM = auto()
    ANIMAL_FRIENDSHIP = auto()
    ANIMAL_MESSENGER = auto()
    AUGURY = auto()
    AURA_OF_VITALITY = auto()
    BARKSKIN = auto()
    BEAST_SENSE = auto()
    CALL_LIGHTNING = auto()
    COMMUNE_WITH_NATURE = auto()
    CONJURE_ANIMALS = auto()
    CONJURE_WOODLAND_ANIMALS = auto()
    CONTINUAL_FLAME = auto()
    CORDON_OF_ARROWS = auto()
    CURE_WOUNDS = auto()
    DARKVISION = auto()
    DAYLIGHT = auto()
    DETECT_MAGIC = auto()
    DETECT_POISON_AND_DISEASE = auto()
    DISPEL_MAGIC = auto()
    DOMINATE_BEAST = auto()
    DRUIDCRAFT = auto()
    ELEMENTALISM = auto()
    ELEMENTAL_WEAPON = auto()
    ENHANCE_ABILITY = auto()
    ENLARGE_REDUCE = auto()
    ENSNARING_STRIKE = auto()
    ENTANGLE = auto()
    FAIRIE_FIRE = auto()
    FEIGN_DEATH = auto()
    FIND_TRAPS = auto()
    FLAME_BLADE = auto()
    FLAMING_SPHERE = auto()
    FOG_CLOUD = auto()
    FREEDOM_OF_MOVEMENT = auto()
    GOODBERRY = auto()
    GREATER_RESTORATION = auto()
    GUIDANCE = auto()
    GUST_OF_WIND = auto()
    HAIL_OF_THORNS = auto()
    HEALING_WORD = auto()
    HEAT_METAL = auto()
    HOLD_PERSON = auto()
    HUNTERS_MARK = auto()
    ICE_KNIFE = auto()
    JUMP = auto()
    LESSER_RESTORATION = auto()
    LOCATE_ANIMALS_OR_PLANTS = auto()
    LOCATE_CREATURE = auto()
    LOCATE_OBJECT = auto()
    LONGSTRIDER = auto()
    MAGIC_WEAPON = auto()
    MELD_INTO_STONE = auto()
    MENDING = auto()
    MESSAGE = auto()
    MOONBEAM = auto()
    NONDETECTION = auto()
    PASS_WITHOUT_TRACE = auto()
    PLANT_GROWTH = auto()
    POISON_SPRAY = auto()
    PRODUCE_FLAME = auto()
    PROTECTION_FROM_ENERGY = auto()
    PROTECTION_FROM_EVIL_AND_GOOD = auto()
    PROTECTION_FROM_POISON = auto()
    PURIFY_FOOD_AND_DRINK = auto()
    RESISTANCE = auto()
    REVIVIFY = auto()
    SHILLELAGH = auto()
    SILENCE = auto()
    SLEET_STORM = auto()
    SPARE_THE_DYING = auto()
    SPEAK_WITH_ANIMALS = auto()
    SPEAK_WITH_PLANTS = auto()
    SPIKE_GROWTH = auto()
    STARRY_WISP = auto()
    STONESKIN = auto()
    SUMMON_BEAST = auto()
    SUMMON_FEY = auto()
    THORN_WHIP = auto()
    THUNDERCLAP = auto()
    THUNDERWAVE = auto()
    TREE_STRIDE = auto()
    WATER_BREATHING = auto()
    WATER_WALK = auto()
    WIND_WALL = auto()


# EOF
