on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: python -m pip install -r requirements-dev.txt

    - name: coverage
      run: |
        make coverage

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      env:
        COVERALLS: ${{ secrets.COVERALLS_REPO_TOKEN }}
